-- Query A1 --
SELECT SUM(COST) FROM PETRESCUE;

-- Query A2 --
SELECT SUM(COST) AS "SUM_OF_COST"
FROM PETRESCUE;

-- QueryA3 --
SELECT MAX(QUANTITY) FROM PETRESCUE;

-- Query A4 --
SELECT AVG(COST) FROM PETRESCUE;

-- Query A5 --
SELECT AVG(COST/QUANTITY)
FROM PETRESCUE
WHERE ANIMAL='Dog';

-- Query B1 --
SELECT ROUND(COST) FROM PETRESCUE;

-- Query B2 --
SELECT LENGTH(ANIMAL) FROM PETRESCUE;

-- Query B3 --
SELECT UCASE(ANIMAL) FROM PETRESCUE;

-- Query B4 --
SELECT DISTINCT(UCASE(ANIMAL)) FROM PETRESCUE;

-- Query B5 --
SELECT * FROM PETRESCUE WHERE LCASE(ANIMAL)='cat';

-- Query C1 --
SELECT DAY(RESCUEDATE) FROM PETRESCUE WHERE LCASE(ANIMAL)='cat';

-- Query C2 --
SELECT SUM(QUANTITY) FROM PETRESCUE WHERE DAY(RESCUEDATE)='5';   

-- Query C3 --
SELECT (RESCUEDATE + 3 DAYS) FROM PETRESCUE ;

-- Query C4 --
SELECT (CURRENT DATE  - RESCUEDATE) FROM PETRESCUE;
 
